# Generated by Django 4.0.3 on 2022-10-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_icon', models.ImageField(upload_to='Amenities_icon')),
                ('amenities_name', models.CharField(max_length=255)),
                ('amenities_type', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('propert_description', models.TextField()),
                ('property_main_image', models.ImageField(upload_to='Property_main_image')),
                ('property_main_floor_plan', models.ImageField(upload_to='Property_main_floor_plan')),
                ('property_address_1', models.TextField()),
                ('property_address_2', models.TextField()),
                ('property_town', models.CharField(max_length=100)),
                ('property_state', models.CharField(max_length=100)),
                ('property_zip', models.CharField(max_length=10)),
                ('property_terms', models.CharField(max_length=100)),
                ('property_offer', models.CharField(max_length=100)),
                ('is_property_fee', models.BooleanField(default=False)),
                ('property_fee', models.CharField(max_length=50, null=True)),
                ('property_listing_amount', models.IntegerField()),
                ('created_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('property_main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprty_type_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('property_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='Property_listing_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_property_exclusive', models.BooleanField(default=False)),
                ('property_listing_start_date', models.DateTimeField()),
                ('property_listing_end_date', models.DateTimeField()),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_detail')),
            ],
        ),
        migrations.AddField(
            model_name='property_detail',
            name='property_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_sub_category'),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_type'),
        ),
        migrations.AddField(
            model_name='property_detail',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='Property_Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_value', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('ameniites_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.amenities_master')),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_detail')),
            ],
        ),
    ]
