# Generated by Django 4.0.3 on 2022-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pasword2',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
