# Generated by Django 4.0.3 on 2022-10-20 11:51

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_pasword2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('mac_address', macaddress.fields.MACAddressField(integer=True)),
                ('location', models.TextField()),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usertype')),
            ],
        ),
    ]
