# Generated by Django 4.0.4 on 2022-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='typep_of_account',
            new_name='type_of_account',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addition_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.JSONField(null=True),
        ),
    ]
